'use client';
import { useEffect } from 'react';
import './landing-page.css';

const BODY_HTML = `

<!-- OFFER TICKER (fixed top) -->
<div class="offer-ticker"><div class="ot-track"><span>₹49 ONLY — 15-DAY TRIAL</span><span>★</span><span>NO HARDWARE NEEDED</span><span>★</span><span>GO LIVE IN 15 MINUTES</span><span>★</span><span>INSTANT WHATSAPP ALERTS</span><span>★</span><span>BUILD YOUR CUSTOMER DATABASE</span><span>★</span><span>₹49 ONLY — 15-DAY TRIAL</span><span>★</span><span>NO HARDWARE NEEDED</span><span>★</span><span>GO LIVE IN 15 MINUTES</span><span>★</span><span>INSTANT WHATSAPP ALERTS</span><span>★</span><span>BUILD YOUR CUSTOMER DATABASE</span><span>★</span></div></div>

<!-- NAV -->
<nav>
  <div class="wrap nav-inner">
    <a href="#" class="logo"><img src="/haivisitor.png" alt="Hai Visitor" class="logo-img" /><span>H<span class="ai-accent">ai</span> VISITOR<small>A visitor management platform by Zodopt</small></span></a>
    <div class="nav-links">
      <a href="#about">About</a>
      <a href="#features">Features</a>
      <a href="#trial">Pricing</a>
      <a href="#faq">FAQ</a>
    </div>
  </div>
</nav>


<!-- 01 · HERO -->
<section class="hero">
  <div class="wrap hero-copy-wrap">
    <div>
      <h1>You spend money bringing customers in. <span class="accent">Don't let their data walk out.</span></h1>
      <p class="hero-copy">Hai Visitor connects the walk-ins generated by your marketing to an organised digital visitor database — so your team has a stronger foundation for future WhatsApp communication and eligible customer-list advertising.</p>
      <ul class="checks">
        <li>QR-based customer registration with no dedicated hardware</li>
        <li>Instant WhatsApp notification to the relevant team member</li>
        <li>Digital visitor records, history, dashboard visibility and reports</li>
      </ul>
      <div class="hero-ctas">
        <a class="btn btn-primary" href="https://rzp.io/rzp/yAdtOdt">Start 15-Day Trial for ₹49 →</a>
      </div>
      <p class="cta-note">Set up in approximately 15 minutes</p>
      </div>
      <div class="hero-figure reveal">
        <div class="photo-card">
          <img src="/hero-checkin-error.jpg" alt="Showroom visitor check-in without a digital record" loading="lazy" />
        </div>
      </div>
    </div>
</section>

<!-- TRUST STRIP -->
<div class="trust">
  <div class="wrap trust-grid">
    <div><b>₹49</b><span>15-day paid trial</span></div>
    <div><b>15 Minutes</b><span>Approximate setup time</span></div>
    <div><b>No Hardware</b><span>Display the QR code</span></div>
    <div><b>AWS-Based</b><span>Cloud-hosted platform</span></div>
  </div>
</div>

<!-- 02 · MARKETING LEAKAGE -->
<section style="background:#fff; border-bottom:1px solid var(--stroke);">
  <div class="wrap split">
    <div>
      <h2>Your marketing brings them in. <span class="accent">What happens after they enter?</span></h2>
      <p class="lede">Meta ads, Google campaigns, influencer promotions and seasonal offers may successfully create showroom footfall. But if the visit is not digitally registered, that customer becomes a missing link in your marketing funnel.</p>
      <div class="points">
        <div class="point"><em>◎</em><span>Your campaigns have already paid to bring attention into the showroom.</span></div>
        <div class="point"><em>↗</em><span>Without structured registration, the relationship may end at the door.</span></div>
        <div class="point"><em>□</em><span>Scattered or incomplete data weakens future communication.</span></div>
        <div class="point"><em>↻</em><span>You may spend again to reach people who already visited.</span></div>
      </div>
      <div class="highlight">The real leakage is not only a missed sale today. It is a customer relationship your future marketing may never be able to use.</div>
    </div>
    <div class="reveal">
      <div class="photo-card"><img src="/marketing-data-gap.jpg" alt="Promotions bring customers in, but they leave with no record captured" loading="lazy" /></div>
      <div class="media-label">Marketing → Walk-In → Data Gap</div>
    </div>
  </div>
</section>

<!-- 03 · WALK-IN INFORMATION GAP -->
<section>
  <div class="wrap split">
    <div class="reveal">
      <div class="photo-card"><img src="/manual-records.jpg" alt="Manual register records" loading="lazy" /></div>
      <div class="media-label">Manual records → Organised database</div>
    </div>
    <div>
      <h2>Every visit deserves more than <span class="accent">a line in a register.</span></h2>
      <p class="lede">Customer information spread across paper registers, spreadsheets, notebooks and individual salespeople is difficult to search, review and use consistently.</p>
      <div class="points">
        <div class="point"><em>▤</em><span>Difficult to retrieve, review and use later.</span></div>
        <div class="point"><em>✎</em><span>Customer information lives in multiple disconnected places.</span></div>
        <div class="point"><em>♙</em><span>Business visibility depends on the person who handled the enquiry.</span></div>
        <div class="point"><em>⌕</em><span>Management cannot easily review registered visits and history.</span></div>
      </div>
    </div>
  </div>
</section>

<!-- 04 · MEET HAI VISITOR -->
<section id="about" style="background:#fff; border-block:1px solid var(--stroke);">
  <div class="wrap split" style="align-items:start;">
    <div>
      <h2>From showroom walk-in to an <span class="accent">organised digital record.</span></h2>
      <p class="lede">A simple, hardware-light visitor flow designed to improve the customer's arrival experience and give the business clearer visitor visibility.</p>
      <div class="flow">
        <div class="flow-step"><em>1</em><span>Customer scans the showroom QR code or opens the registration link.</span></div>
        <div class="flow-step"><em>2</em><span>Customer submits the required visitor details.</span></div>
        <div class="flow-step"><em>3</em><span>The relevant team member receives a WhatsApp notification.</span></div>
        <div class="flow-step"><em>4</em><span>The visitor entry becomes part of the digital visitor history.</span></div>
        <div class="flow-step"><em>5</em><span>Authorised users access dashboard visibility and reports.</span></div>
      </div>
    </div>
    <div class="tracker reveal">
      <div class="tr-head"><b>Live visitor log — what your team sees</b><span class="live">LIVE</span></div>
      <div class="tr-body">
        <div class="tr-track">
          <div class="tr-row"><div class="tr-av" style="background:#221C53">RH</div><div class="tr-meta"><b>Ramesh H.</b><span>Sofa set · 3-seater · Host: Suresh</span></div><span class="tr-tag">CAPTURED</span></div>
          <div class="tr-row"><div class="tr-av" style="background:#7C2D4E">AS</div><div class="tr-meta"><b>Anita S.</b><span>Modular kitchen enquiry · Host: Divya</span></div><span class="tr-tag">CAPTURED</span></div>
          <div class="tr-row"><div class="tr-av" style="background:#0E7490">VM</div><div class="tr-meta"><b>Vikram M.</b><span>Tiles · 2BHK project · Host: Suresh</span></div><span class="tr-tag alert">TEAM ALERTED</span></div>
          <div class="tr-row"><div class="tr-av" style="background:#B45309">PN</div><div class="tr-meta"><b>Priya N.</b><span>Bridal lehenga trial · Host: Meera</span></div><span class="tr-tag">CAPTURED</span></div>
          <div class="tr-row"><div class="tr-av" style="background:#166534">KR</div><div class="tr-meta"><b>Karthik R.</b><span>Test drive enquiry · Host: Arjun</span></div><span class="tr-tag alert">TEAM ALERTED</span></div>
          <div class="tr-row"><div class="tr-av" style="background:#6D28D9">SD</div><div class="tr-meta"><b>Sneha D.</b><span>Wardrobe & lighting · Host: Divya</span></div><span class="tr-tag">CAPTURED</span></div>
          <div class="tr-row"><div class="tr-av" style="background:#9F1239">MI</div><div class="tr-meta"><b>Mohan I.</b><span>Recliner enquiry · Host: Suresh</span></div><span class="tr-tag">CAPTURED</span></div>
          <div class="tr-row"><div class="tr-av" style="background:#1D4ED8">LB</div><div class="tr-meta"><b>Lakshmi B.</b><span>Sanitaryware · Villa project · Host: Meera</span></div><span class="tr-tag alert">TEAM ALERTED</span></div>
          <div class="tr-row"><div class="tr-av" style="background:#221C53">RH</div><div class="tr-meta"><b>Ramesh H.</b><span>Sofa set · 3-seater · Host: Suresh</span></div><span class="tr-tag">CAPTURED</span></div>
          <div class="tr-row"><div class="tr-av" style="background:#7C2D4E">AS</div><div class="tr-meta"><b>Anita S.</b><span>Modular kitchen enquiry · Host: Divya</span></div><span class="tr-tag">CAPTURED</span></div>
          <div class="tr-row"><div class="tr-av" style="background:#0E7490">VM</div><div class="tr-meta"><b>Vikram M.</b><span>Tiles · 2BHK project · Host: Suresh</span></div><span class="tr-tag alert">TEAM ALERTED</span></div>
          <div class="tr-row"><div class="tr-av" style="background:#B45309">PN</div><div class="tr-meta"><b>Priya N.</b><span>Bridal lehenga trial · Host: Meera</span></div><span class="tr-tag">CAPTURED</span></div>
          <div class="tr-row"><div class="tr-av" style="background:#166534">KR</div><div class="tr-meta"><b>Karthik R.</b><span>Test drive enquiry · Host: Arjun</span></div><span class="tr-tag alert">TEAM ALERTED</span></div>
          <div class="tr-row"><div class="tr-av" style="background:#6D28D9">SD</div><div class="tr-meta"><b>Sneha D.</b><span>Wardrobe & lighting · Host: Divya</span></div><span class="tr-tag">CAPTURED</span></div>
          <div class="tr-row"><div class="tr-av" style="background:#9F1239">MI</div><div class="tr-meta"><b>Mohan I.</b><span>Recliner enquiry · Host: Suresh</span></div><span class="tr-tag">CAPTURED</span></div>
          <div class="tr-row"><div class="tr-av" style="background:#1D4ED8">LB</div><div class="tr-meta"><b>Lakshmi B.</b><span>Sanitaryware · Villa project · Host: Meera</span></div><span class="tr-tag alert">TEAM ALERTED</span></div>
        </div>
      </div>
      <div class="tr-foot">Every registered walk-in appears here instantly — searchable, exportable and never lost in a register.</div>
    </div>
  </div>
  <div class="wrap reveal" style="margin-top:2.4rem;">
    <div class="device-showcase">
      <div class="device-row">
        <div class="device-phone">
          <div class="frame"><div class="notch"></div><div class="screen"><img src="/qr%20code%20screen.png" alt="Hai Visitor QR registration screen" loading="lazy" /></div></div>
        </div>
        <div class="device-laptop">
          <div class="lid"><div class="screen"><img src="/Actual%20Promeet%20Dashbaord.png" alt="Hai Visitor dashboard screen" loading="lazy" /></div></div>
          <div class="base"></div>
        </div>
        <div class="device-phone">
          <div class="frame"><div class="notch"></div><div class="screen"><img src="/pic%20(2).png" alt="Hai Visitor WhatsApp notification screen" loading="lazy" /></div></div>
        </div>
      </div>
      <div class="step-icons-row">
        <div class="step-icon"><span class="num-badge">1</span><span class="icon-box"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><rect width="5" height="5" x="3" y="3" rx="1"/><rect width="5" height="5" x="16" y="3" rx="1"/><rect width="5" height="5" x="3" y="16" rx="1"/><path d="M21 16h-3a2 2 0 0 0-2 2v3"/><path d="M21 21v.01"/><path d="M12 7v3a2 2 0 0 1-2 2H7"/><path d="M3 12h.01"/><path d="M12 3h.01"/><path d="M12 16v.01"/><path d="M16 12h1"/><path d="M21 12v.01"/><path d="M12 21v-1"/></svg></span><span class="step-label">Scan QR</span></div>
        <span class="step-arrow">→</span>
        <div class="step-icon"><span class="num-badge">2</span><span class="icon-box"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><rect x="8" y="2" width="8" height="4" rx="1" ry="1"/><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"/><path d="M9 12h6M9 16h6M9 8h1"/></svg></span><span class="step-label">Complete Registration</span></div>
        <span class="step-arrow">→</span>
        <div class="step-icon"><span class="num-badge">3</span><span class="icon-box"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z"/></svg></span><span class="step-label">Team Member Notified</span></div>
        <span class="step-arrow">→</span>
        <div class="step-icon"><span class="num-badge">4</span><span class="icon-box"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><path d="M22 4 12 14.01l-3-3"/></svg></span><span class="step-label">Visitor Record Saved</span></div>
        <span class="step-arrow">→</span>
        <div class="step-icon"><span class="num-badge">5</span><span class="icon-box"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"><path d="M3 3v18h18"/><path d="M18 17V9M13 17V5M8 17v-3"/></svg></span><span class="step-label">Dashboard &amp; Reports</span></div>
      </div>
    </div>
  </div>
</section>

<!-- 05 · FROM VISIT TO FUTURE OPPORTUNITY -->
<section>
  <div class="wrap center">
    <h2>A customer may leave today. <span class="accent">Their visit record doesn't have to.</span></h2>
    <p class="lede">A registered walk-in becomes a retrievable visitor record that the authorised showroom team can reference later instead of allowing the relationship to disappear into paper or memory.</p>
    <div class="split" style="margin-top:1.6rem; text-align:left; align-items:start;">
      <div class="points" style="margin-top:0">
        <div class="point"><em>◍</em><span>Use visitor history and reports to see the records your business captured.</span></div>
        <div class="point"><em>✆</em><span>Contact consented customers later using your chosen marketing workflow.</span></div>
      </div>
      <div class="points" style="margin-top:0">
        <div class="point"><em>↗</em><span>Where eligible, upload consented records to advertising platforms under applicable policies.</span></div>
        <div class="point"><em>✦</em><span>Give your team a stronger database foundation for relevant future communication.</span></div>
      </div>
    </div>
    <div class="highlight" style="max-width:640px; margin-inline:auto; text-align:left;">Hai Visitor organises the visit. Your team decides the next relevant customer action.</div>
  </div>
</section>

<!-- 06 · NEW & FUTURE CUSTOMER OPPORTUNITIES -->
<section style="background:#fff; border-block:1px solid var(--stroke);">
  <div class="wrap center">
    <h2>One organised database. <span class="accent">Two practical marketing uses.</span></h2>
    <p class="lede">Hai Visitor helps your showroom retain registered walk-in information in one place. That gives your authorised team a cleaner foundation to manage today's visitors and responsibly re-engage consented customers later.</p>
    <div class="split" style="margin-top:1.8rem; text-align:left; align-items:start;">
      <div class="points" style="margin-top:0">
        <div class="point"><em>▦</em><span>Notify the relevant staff member and maintain an organised digital visitor record.</span></div>
        <div class="point"><em>✆</em><span>Use consented records later through your separate WhatsApp marketing process.</span></div>
      </div>
      <div class="points" style="margin-top:0">
        <div class="point"><em>◉</em><span>Where permitted, use consented customer lists under the advertising platform's policies.</span></div>
        <div class="point"><em>✦</em><span>Reduce dependence on starting every customer relationship from zero.</span></div>
      </div>
    </div>
    <div class="highlight" style="max-width:680px; margin-inline:auto; text-align:left;">Hai Visitor closes the gap between customers your marketing has already reached and the database your future marketing needs.</div>
  </div>
</section>

<!-- 07 · AI-BASED POSITIONING -->
<section class="dark">
  <div class="wrap center">
    <h2>Build the structured data foundation your <span class="accent">future marketing intelligence needs.</span></h2>
    <p class="lede">AI cannot create value from customer information your business never captures. Hai Visitor helps convert registered showroom visits into a structured visitor-data foundation that can support the brand's broader AI and marketing roadmap.</p>
    <div class="layer-grid" style="text-align:left">
      <div class="layer reveal"><span class="chip"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="5" height="5" x="3" y="3" rx="1"/><rect width="5" height="5" x="16" y="3" rx="1"/><rect width="5" height="5" x="3" y="16" rx="1"/><path d="M21 16h-3a2 2 0 0 0-2 2v3"/><path d="M21 21v.01"/><path d="M12 7v3a2 2 0 0 1-2 2H7"/><path d="M3 12h.01"/><path d="M12 3h.01"/><path d="M12 16v.01"/><path d="M16 12h1"/><path d="M21 12v.01"/><path d="M12 21v-1"/></svg></span><h3>Consented visitor registration</h3><p>Name, phone and relevant visit fields</p><span class="tag">Capture</span></div>
      <div class="layer reveal"><span class="chip"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M3 5v14a9 3 0 0 0 18 0V5"/><path d="M3 12a9 3 0 0 0 18 0"/></svg></span><h3>Organised visitor records</h3><p>One retrievable source for authorised teams</p><span class="tag">Organise</span></div>
      <div class="layer reveal"><span class="chip"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z"/></svg></span><h3>Team-led WhatsApp use</h3><p>External outreach based on consent and policy</p><span class="tag">Activate</span></div>
      <div class="layer reveal"><span class="chip"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m3 11 18-5v12L3 14v-3z"/><path d="M11.6 16.8a3 3 0 1 1-5.8-1.6"/></svg></span><h3>Eligible advertising audiences</h3><p>Customer-list use subject to platform requirements</p><span class="tag">Retarget</span></div>
    </div>
    <div class="highlight highlight-nowrap" style="margin-inline:auto; text-align:left;">Capture first. Organise consistently. Activate through approved external marketing workflows.</div>
  </div>
</section>

<!-- 08 · BUILT FOR HIGH-VALUE RETAIL -->
<section>
  <div class="wrap center">
    <h2>One visitor-management foundation. <span class="accent">Four priority showroom segments.</span></h2>
    <p class="lede">Designed for businesses where physical walk-ins, assisted buying, longer consideration cycles and follow-up all matter.</p>
    <div class="reveal" style="margin-top:2rem">
      <div class="photo-card">
        <div class="seg-photo-grid">
          <div class="seg-photo"><img src="/bridal-jewellery.jpg" alt="Fashion, Bridal &amp; Jewellery showroom" loading="lazy" /><span class="photo-tag">Fashion &amp; Bridal</span></div>
          <div class="seg-photo"><img src="/automobile.png" alt="Premium Automobile showroom" loading="lazy" /><span class="photo-tag">Premium Auto</span></div>
          <div class="seg-photo"><img src="/home-interiors.jpg" alt="Home &amp; Interiors showroom" loading="lazy" /><span class="photo-tag">Home &amp; Interiors</span></div>
          <div class="seg-photo"><img src="/offices.jpg" alt="Offices" loading="lazy" /><span class="photo-tag">Offices</span></div>
        </div>
      </div>
      <div class="media-label">Four priority showroom segments</div>
    </div>
  </div>
</section>

<!-- 09 · PRODUCT FEATURES -->
<section id="features" style="background:#fff; border-block:1px solid var(--stroke);">
  <div class="wrap center">
    <h2>Simple enough to start quickly. <span class="accent">Useful enough to replace manual chaos.</span></h2>
    <div class="feat-grid2" style="text-align:left">
      <div class="feat2 reveal"><b>QR Registration</b><span>Walk-in and pre-registration workflows.</span></div>
      <div class="feat2 reveal"><b>WhatsApp Notification</b><span>Alert the person selected by the visitor.</span></div>
      <div class="feat2 reveal"><b>Digital Visitor Pass</b><span>Delivered through WhatsApp after registration.</span></div>
      <div class="feat2 reveal"><b>Visitor History</b><span>Retrieve registered visit information.</span></div>
      <div class="feat2 reveal"><b>Check-In / Check-Out</b><span>Maintain entry and exit records.</span></div>
      <div class="feat2 reveal"><b>Dashboard &amp; Reports</b><span>Review visitors, hosts and consolidated activity.</span></div>
      <div class="feat2 reveal"><b>Conference Booking</b><span>Manage meeting rooms within the platform.</span></div>
      <div class="feat2 reveal"><b>Multi-Location Support</b><span>Available with current product limitations.</span></div>
      <div class="feat2 reveal"><b>No Dedicated Hardware</b><span>The minimum setup is a displayed QR code.</span></div>
    </div>
    <div class="screens-row reveal">
      <div class="flip-card">
        <div class="flip-inner">
          <div class="flip-face"><img src="/pic%20(1).jpeg" alt="Hai Visitor digital visitor pass screen" loading="lazy" /></div>
          <div class="flip-face flip-back"><img src="/pic%20(2).png" alt="Hai Visitor WhatsApp pass notification screen" loading="lazy" /></div>
        </div>
      </div>
      <img src="/Home%20screen.png" alt="Hai Visitor home screen" loading="lazy" />
    </div>
  </div>
</section>

<!-- 10 · BEFORE VS WITH HAI VISITOR -->
<section>
  <div class="wrap center">
    <h2>Move from disconnected visitor handling to <span class="accent">one organised workflow.</span></h2>
    <div class="vs-grid">
      <div class="vs-card old reveal">
        <span class="vs-tag">Before Hai Visitor</span>
        <ul>
          <li>Paper registers and scattered spreadsheets</li>
          <li>Manual calls to find the relevant staff member</li>
          <li>Visitor information difficult to retrieve later</li>
          <li>Limited check-in and check-out visibility</li>
          <li>Marketing-generated walk-ins remain disconnected</li>
        </ul>
      </div>
      <div class="vs-card new reveal">
        <span class="vs-tag">With Hai Visitor</span>
        <ul>
          <li>QR-based digital visitor registration</li>
          <li>WhatsApp notification to the selected team member</li>
          <li>Organised visitor records and history</li>
          <li>Dashboard, check-in/check-out and reports</li>
          <li>Stronger data foundation for future marketing use</li>
        </ul>
      </div>
    </div>
  </div>
</section>

<!-- 11 · OFFER -->
<section id="trial" style="background:#fff; border-block:1px solid var(--stroke);">
  <div class="wrap">
    <div class="offer-grid">
      <div>
        <h2>Try Hai Visitor in your showroom for <span class="accent">15 days at ₹49.</span></h2>
        <p class="lede">Set up the QR workflow, register live visitors and see how organised digital visitor management fits into your showroom operation.</p>
        <div class="points">
          <div class="point"><em>15</em><span>Create the account, users, hosts, rooms and QR workflow.</span></div>
          <div class="point"><em>∞</em><span>Confirmed base plan after the paid trial; terms apply.</span></div>
        </div>
      </div>
      <div class="offer-card reveal">
        <div class="burst">JUST<br />₹49</div>
        <div class="price-label">15-Day Hai Visitor Trial</div>
        <div class="price">₹49</div>
        <div class="one">one time</div>
        <ul>
          <li>100 visitor bookings</li>
          <li>100 conference bookings</li>
          <li>2 conference rooms</li>
          <li>No dedicated hardware required</li>
        </ul>
        <a class="btn btn-primary" href="https://rzp.io/rzp/yAdtOdt">Start Your 15-Day Trial →</a>
        <div class="micro">Paid trial · No refund · Product terms apply</div>
      </div>
    </div>
  </div>
</section>

<!-- 12 · FAQ -->
<section id="faq">
  <div class="wrap center">
    <h2>Everything a showroom owner needs to know <span class="accent">before starting.</span></h2>
    <div class="faq-grid">
      <details>
        <summary>Do we need to purchase any hardware?</summary>
        <p>No dedicated hardware is required. The confirmed minimum setup is to display the Hai Visitor QR code for visitors to scan with their phone.</p>
      </details>
      <details>
        <summary>How quickly can we start using Hai Visitor?</summary>
        <p>The standard setup can be completed in approximately 15 minutes, including account creation, user or host setup, QR generation and room configuration. Larger enterprise requirements may take longer.</p>
      </details>
      <details>
        <summary>Does Hai Visitor automatically run WhatsApp marketing or ads?</summary>
        <p>No. Hai Visitor captures and organises registered visitor information. Your authorised team may use consented data in separate WhatsApp or advertising workflows, subject to applicable law and each platform's policies.</p>
      </details>
      <details>
        <summary>Can Hai Visitor track what a customer wanted or whether they purchased?</summary>
        <p>These are not confirmed standard capabilities. Hai Visitor records the visitor information and visit workflow supported by the product; it should not be presented as a purchase-intent or sales-conversion tracker.</p>
      </details>
      <details>
        <summary>What happens after the 15-day trial?</summary>
        <p>The confirmed Business plan is ₹500 per month. A 10-day buffer period follows the trial before moving to the Business plan. Final billing and renewal terms should be shown at checkout.</p>
      </details>
      <details>
        <summary>Can we use Hai Visitor across multiple locations?</summary>
        <p>Multi-location support is available, with limitations. Pricing is indicated per location, and the exact configuration should be confirmed for your business.</p>
      </details>
    </div>
  </div>
</section>

<!-- 13 · CLOSE THE SHOWROOM DATA GAP -->
<section style="padding-top:0">
  <div class="wrap">
    <div class="final reveal">
      <h2>Your marketing has already brought the customer in. <span class="accent">Make the visit count beyond today.</span></h2>
      <p class="lede">Replace fragmented walk-in records with a simple digital visitor-management foundation that your team can retrieve, review and responsibly use.</p>
      <div class="hero-ctas">
        <a class="btn btn-primary" href="https://rzp.io/rzp/yAdtOdt">Start 15-Day Trial for ₹49 →</a>
        <a class="btn btn-wa" href="https://wa.me/916366834745?text=Hi%2C+Can+i+know+more+about+Hai+Visitor+-+Visitor+Management+Platform" target="_blank" rel="noopener noreferrer">Chat with the Hai Visitor Team</a>
      </div>
    </div>
  </div>
</section>

<!-- FOOTER -->
<footer>
  <div class="wrap foot-bottom">
    <span>© 2026 Zodopt's Hai Visitor. All rights reserved.</span>
    <a href="https://zodopt.com/about-us/" target="_blank" rel="noopener noreferrer">© Zodopt</a>
    <div class="foot-links">
      <a href="https://zodopt.com/privacy-policy/" target="_blank" rel="noopener noreferrer">Privacy Policy</a>
      <a href="https://zodopt.com/terms-and-conditions/" target="_blank" rel="noopener noreferrer">Terms and Conditions</a>
    </div>
  </div>
</footer>

<!-- STICKY CTA (all screen sizes) -->
<div class="sticky-cta">
  <a class="btn btn-primary" href="https://rzp.io/rzp/yAdtOdt">Start 15-Day Trial for ₹49 →</a>
</div>

<!-- WhatsApp float (desktop) -->
<a class="wa-float" href="https://wa.me/916366834745?text=Hi%2C+Can+i+know+more+about+Hai+Visitor+-+Visitor+Management+Platform" target="_blank" rel="noopener noreferrer" aria-label="Chat on WhatsApp"><img src="/whatsapp-icon.png" alt="WhatsApp" /></a>

`;

export default function HomePage() {
  useEffect(() => {
    document.documentElement.classList.add('js');

    /* ── Reveal-on-scroll ─────────────────────────────── */
    let io;
    const revealTimer = setTimeout(() => {
      document.querySelectorAll('.reveal:not(.vis)').forEach(el => el.classList.add('vis'));
    }, 2500);
    if ('IntersectionObserver' in window) {
      io = new IntersectionObserver(entries => {
        entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('vis'); io.unobserve(e.target); } });
      }, { threshold: 0.12 });
      document.querySelectorAll('.reveal').forEach(el => io.observe(el));
    }

    /* ── Auto-flip screenshot card every 5s ──────────── */
    const flipCard = document.querySelector('.flip-card');
    let flipTimer;
    if (flipCard) {
      flipTimer = setInterval(() => {
        const inner = flipCard.querySelector('.flip-inner');
        inner.style.transform = inner.style.transform === 'rotateY(180deg)' ? 'rotateY(0deg)' : 'rotateY(180deg)';
      }, 5000);
    }

    return () => {
      clearTimeout(revealTimer);
      if (flipTimer) clearInterval(flipTimer);
      if (io) io.disconnect();
    };
  }, []);

  return <div dangerouslySetInnerHTML={{ __html: BODY_HTML }} />;
}
