'use client';
import { useEffect } from 'react';
import { TRIAL_MODAL_HTML, initTrialSignup, loadMetaPixel } from '../components/trialSignup';
import '../components/industry-tailwind.css';
import '../components/industry-landing.css';
import './furniture.css';

/* Furniture landing page. The markup is the design export
   (hai-visitor-website-furniture/index.html) as-is, with the site's logo, the
   shared trial popup, sticky trial bar and WhatsApp button added, and step 02
   of the walkthrough filled in (the export repeats step 01 there). Every
   "Start trial" button carries `trial-cta`, which opens the same popup as the
   main landing page; signups from here are tagged 'furniture'. */

const WHATSAPP_URL =
  'https://wa.me/916366834745?text=' +
  encodeURIComponent('Hi, Can i know more about Hai Visitor - Visitor Management Platform');

const BODY_HTML = `
<main id="top" class="min-h-screen overflow-hidden bg-background text-foreground"><div class="brand-intro" aria-hidden="true"><div class="brand-intro__mark"><span class="brand-intro__emblem fu-logo"><img src="/v-mark.png" alt="" /></span><span class="brand-intro__name">H<span>ai</span> Visitor</span></div></div><a href="#content" class="fixed left-3 top-3 z-[70] -translate-y-24 bg-primary px-4 py-2 text-primary-foreground focus:translate-y-0">Skip to main content</a>
<header class="absolute inset-x-0 top-0 z-40 border-b border-paper/20 bg-ink/40 text-paper backdrop-blur-md"><nav class="section-shell flex h-20 items-center justify-between" aria-label="Main navigation"><a href="#top" class="brand-lockup  text-paper" aria-label="Hai Visitor home"><span class="brand-lockup__emblem fu-logo" aria-hidden="true"><img src="/v-mark.png" alt="" /></span><span class="brand-lockup__name">H<span>ai</span> Visitor</span></a><div class="hidden items-center gap-8 md:flex"><a class="text-sm text-paper/70 transition-colors hover:text-primary" href="#how-it-works">How it works</a><a class="text-sm text-paper/70 transition-colors hover:text-primary" href="#walkthrough">Walkthrough</a><a class="text-sm text-paper/70 transition-colors hover:text-primary" href="#why">Why Hai Visitor</a><a href="#trial" class="trial-cta inline-flex items-center justify-center gap-3 rounded-sm text-sm font-semibold transition-all duration-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:pointer-events-none disabled:opacity-50 border bg-transparent hover:border-primary hover:text-primary min-h-12 px-6 border-paper/35 text-paper">Start trial <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-arrow-up-right size-4" aria-hidden="true"><path d="M7 7h10v10"></path><path d="M7 17 17 7"></path></svg></a></div></nav></header>
<section id="content" class="relative min-h-[720px] bg-ink pt-20 text-paper"><img src="/jewellery/hero.jpg" alt="An Indian customer trying earrings with a showroom associate in a jewellery showroom" width="1920" height="1088" class="hero-image absolute inset-0 size-full object-cover object-center"/><div class="hero-veil absolute inset-0"></div>
<div class="section-shell relative flex min-h-[640px] items-center py-16"><div class="max-w-2xl animate-rise"><p class="mb-7 text-xs font-semibold uppercase tracking-[0.28em] text-primary">VIBE · Visit. Interact. Build. Engage.</p><h1 class="max-w-[10ch] text-6xl leading-[0.98] tracking-normal sm:text-7xl lg:text-8xl">Every visit is worth <em class="text-primary">remembering.</em></h1><p class="mt-7 max-w-xl text-lg leading-8 text-paper/75">Register in-store walk-ins, alert the right team member and keep visitor records ready for your next conversation.</p><div class="mt-9 flex flex-wrap gap-4"><a href="#trial" class="trial-cta inline-flex items-center justify-center gap-3 rounded-sm font-semibold transition-all duration-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:-translate-y-0.5 hover:bg-primary/90 min-h-14 px-8 text-base">Start 15-day trial @ ₹49 <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-arrow-up-right size-5" aria-hidden="true"><path d="M7 7h10v10"></path><path d="M7 17 17 7"></path></svg></a><a href="#how-it-works" class="inline-flex items-center justify-center gap-3 rounded-sm font-semibold transition-all duration-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:pointer-events-none disabled:opacity-50 border bg-transparent hover:border-primary hover:text-primary min-h-14 px-8 text-base border-paper/35 text-paper">See how it works <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-arrow-down size-5" aria-hidden="true"><path d="M12 5v14"></path><path d="m19 12-7 7-7-7"></path></svg></a></div><p class="mt-4 text-xs text-paper/55">15-day paid trial · 100 visitor bookings included</p></div></div>
</section>
<section id="how-it-works" class="bg-paper py-20 lg:py-28">
<div class="section-shell"><div class="max-w-3xl"><p class="text-xs font-semibold uppercase tracking-[0.25em] text-primary">The VIBE approach</p><h2 class="mt-5 text-5xl leading-tight tracking-normal lg:text-6xl">From first visit to a better next conversation.</h2><p class="mt-7 max-w-2xl leading-7 text-muted-foreground">A simple in-store process makes visitor details available to the people serving them, while every later conversation remains personal and permission-led.</p></div><div class="mt-14 grid gap-4 md:grid-cols-3">
<article class="journey-card group journey-card--capture"><div class="flex items-start justify-between"><span class="text-xs font-semibold tracking-[0.2em]">01 / CAPTURE</span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-qr-code size-7" aria-hidden="true"><rect width="5" height="5" x="3" y="3" rx="1"></rect><rect width="5" height="5" x="16" y="3" rx="1"></rect><rect width="5" height="5" x="3" y="16" rx="1"></rect><path d="M21 16h-3a2 2 0 0 0-2 2v3"></path><path d="M21 21v.01"></path><path d="M12 7v3a2 2 0 0 1-2 2H7"></path><path d="M3 12h.01"></path><path d="M12 3h.01"></path><path d="M12 16v.01"></path><path d="M16 12h1"></path><path d="M21 12v.01"></path><path d="M12 21v-1"></path></svg></div><h3 class="mt-16 font-display text-3xl">Register the visit.</h3><p class="mt-4 text-sm leading-6 opacity-75">A customer scans the showroom’s QR and enters their details.</p><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-right mt-9 size-5 transition-transform duration-300 group-hover:translate-x-2" aria-hidden="true"><path d="m9 18 6-6-6-6"></path></svg></article>
<article class="journey-card group journey-card--connect"><div class="flex items-start justify-between"><span class="text-xs font-semibold tracking-[0.2em]">02 / CONNECT</span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-database size-7" aria-hidden="true"><ellipse cx="12" cy="5" rx="9" ry="3"></ellipse><path d="M3 5V19A9 3 0 0 0 21 19V5"></path><path d="M3 12A9 3 0 0 0 21 12"></path></svg></div><h3 class="mt-16 font-display text-3xl">Keep the record.</h3><p class="mt-4 text-sm leading-6 opacity-75">Saved visitor details stay available to the team for a better next conversation.</p><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-right mt-9 size-5 transition-transform duration-300 group-hover:translate-x-2" aria-hidden="true"><path d="m9 18 6-6-6-6"></path></svg></article>
<article class="journey-card group journey-card--engage"><div class="flex items-start justify-between"><span class="text-xs font-semibold tracking-[0.2em]">03 / ENGAGE</span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-message-circle size-7" aria-hidden="true"><path d="M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719"></path></svg></div><h3 class="mt-16 font-display text-3xl">Brand WhatsApp opt-in.</h3><p class="mt-4 text-sm leading-6 opacity-75">Visitors choose whether your authorised team can reconnect through your brand’s WhatsApp channel.</p><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chevron-right mt-9 size-5 transition-transform duration-300 group-hover:translate-x-2" aria-hidden="true"><path d="m9 18 6-6-6-6"></path></svg></article></div></div>
</section>
<section class="border-y border-border bg-primary py-20 text-ink lg:py-24">
<div class="section-shell"><div class="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p class="text-xs font-semibold uppercase tracking-[0.22em] text-deep">The first interaction matters</p><h2 class="mt-4 max-w-2xl text-4xl tracking-normal lg:text-5xl">Built for considered showroom visits.</h2></div><p class="max-w-md text-sm leading-6 text-muted-foreground">The QR belongs inside your showroom. Your team stays part of the experience.</p></div><div class="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
<article class="industry-card industry-card--fashion"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-shirt size-7" aria-hidden="true"><path d="M20.38 3.46 16 2a4 4 0 0 1-8 0L3.62 3.46a2 2 0 0 0-1.34 2.23l.58 3.47a1 1 0 0 0 .99.84H6v10c0 1.1.9 2 2 2h8a2 2 0 0 0 2-2V10h2.15a1 1 0 0 0 .99-.84l.58-3.47a2 2 0 0 0-1.34-2.23z"></path></svg><div><h3 class="text-lg font-semibold">Fashion</h3><p class="mt-2 text-xs leading-5 opacity-70">Personal attention, remembered.</p></div></article>
<article class="industry-card industry-card--jewellery"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-gem size-7" aria-hidden="true"><path d="M10.5 3 8 9l4 13 4-13-2.5-6"></path><path d="M17 3a2 2 0 0 1 1.6.8l3 4a2 2 0 0 1 .013 2.382l-7.99 10.986a2 2 0 0 1-3.247 0l-7.99-10.986A2 2 0 0 1 2.4 7.8l2.998-3.997A2 2 0 0 1 7 3z"></path><path d="M2 9h20"></path></svg><div><h3 class="text-lg font-semibold">Jewellery</h3><p class="mt-2 text-xs leading-5 opacity-70">Considered visits, thoughtfully recorded.</p></div></article>
<article class="industry-card industry-card--automobile"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-car-front size-7" aria-hidden="true"><path d="m21 8-2 2-1.5-3.7A2 2 0 0 0 15.646 5H8.4a2 2 0 0 0-1.903 1.257L5 10 3 8"></path><path d="M7 14h.01"></path><path d="M17 14h.01"></path><rect width="18" height="8" x="3" y="10" rx="2"></rect><path d="M5 18v2"></path><path d="M19 18v2"></path></svg><div><h3 class="text-lg font-semibold">Premium automobile</h3><p class="mt-2 text-xs leading-5 opacity-70">Every showroom conversation in view.</p></div></article>
<article class="industry-card industry-card--interiors industry-card--featured"><span class="fu-tag">Featured</span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-sofa size-7" aria-hidden="true"><path d="M20 9V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v3"></path><path d="M2 16a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-5a2 2 0 0 0-4 0v1.5a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5V11a2 2 0 0 0-4 0z"></path><path d="M4 18v2"></path><path d="M20 18v2"></path><path d="M12 4v9"></path></svg><div><h3 class="text-lg font-semibold">Home &amp; interiors</h3><p class="mt-2 text-xs leading-5 opacity-70">Longer journeys, easier continuity.</p></div></article></div></div>
</section>
<section id="walkthrough" class="bg-ink py-20 text-paper lg:py-28">
<div class="section-shell"><div class="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p class="text-xs font-semibold uppercase tracking-[0.25em] text-sky">A look inside the visit</p><h2 class="mt-4 text-5xl tracking-normal">Four steps. One clear process.</h2></div><p class="max-w-md text-sm leading-6 text-muted-foreground">Explore the in-store journey. The screen shown is an illustrative workflow, with dummy data only.</p></div><div role="tablist" aria-label="Visitor journey" class="grid grid-cols-2 border border-paper/20 sm:grid-cols-4"><button role="tab" data-tab-index="0" aria-selected="true" class="min-h-20 border-r border-paper/20 px-4 text-left text-sm transition-colors last:border-r-0 bg-primary text-primary-foreground"><span class="block text-xs opacity-60">01</span>Scan in-store</button><button role="tab" data-tab-index="1" aria-selected="false" class="min-h-20 border-r border-paper/20 px-4 text-left text-sm transition-colors last:border-r-0 bg-ink text-paper/65 hover:bg-paper hover:text-ink"><span class="block text-xs opacity-60">02</span>Register</button><button role="tab" data-tab-index="2" aria-selected="false" class="min-h-20 border-r border-paper/20 px-4 text-left text-sm transition-colors last:border-r-0 bg-ink text-paper/65 hover:bg-paper hover:text-ink"><span class="block text-xs opacity-60">03</span>Choose opt-in</button><button role="tab" data-tab-index="3" aria-selected="false" class="min-h-20 border-r border-paper/20 px-4 text-left text-sm transition-colors last:border-r-0 bg-ink text-paper/65 hover:bg-paper hover:text-ink"><span class="block text-xs opacity-60">04</span>WhatsApp</button></div>
<div data-panel-index="0" class="grid min-h-[520px] border-x border-b border-paper/20 lg:grid-cols-[1.2fr_.8fr]"><div class="relative flex items-center justify-center overflow-hidden bg-ink p-8"><img src="/jewellery/showroom.jpg" alt="Customer using a showroom QR registration point" class="absolute inset-0 size-full object-cover opacity-40 grayscale"><div class="relative animate-drift w-[260px] border border-paper/20 bg-background p-3 shadow-2xl"><div class="min-h-[420px] border border-border bg-card p-7"><p class="text-[10px] font-semibold uppercase tracking-[0.2em] text-primary">AT YOUR SHOWROOM</p><h3 class="mt-3 font-display text-3xl">Scan to register your visit</h3><div class="mt-10 grid min-h-48 place-items-center border border-dashed border-border bg-background/50 p-4"><div class="flex flex-col items-center gap-3"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-qr-code size-24 text-primary" aria-hidden="true"><rect width="5" height="5" x="3" y="3" rx="1"></rect><rect width="5" height="5" x="16" y="3" rx="1"></rect><rect width="5" height="5" x="3" y="16" rx="1"></rect><path d="M21 16h-3a2 2 0 0 0-2 2v3"></path><path d="M21 21v.01"></path><path d="M12 7v3a2 2 0 0 1-2 2H7"></path><path d="M3 12h.01"></path><path d="M12 3h.01"></path><path d="M12 16v.01"></path><path d="M16 12h1"></path><path d="M21 12v.01"></path><path d="M12 21v-1"></path></svg><p class="text-[10px] uppercase tracking-[0.15em] text-muted-foreground">Counter 03 · Mumbai showroom</p></div></div></div></div></div><div class="flex flex-col justify-center bg-paper p-8 text-ink md:p-12"><p class="text-xs font-semibold tracking-[0.2em] text-primary">STEP 01 / 04</p><h3 class="mt-5 font-display text-4xl">An easy welcome.</h3><p class="mt-5 max-w-md leading-7 text-ink/65">The visitor scans a QR displayed at your showroom counter. This visual is a non-functional placeholder.</p><p class="mt-10 border-t border-ink/15 pt-5 text-xs text-ink/60">Illustrative product flow · This QR is not a registration link</p></div></div>
<div data-panel-index="1" hidden class="grid min-h-[520px] border-x border-b border-paper/20 lg:grid-cols-[1.2fr_.8fr]"><div class="relative flex items-center justify-center overflow-hidden bg-ink p-8"><img src="/jewellery/showroom.jpg" alt="Customer using a showroom QR registration point" class="absolute inset-0 size-full object-cover opacity-40 grayscale"/><div class="relative animate-drift w-[260px] border border-paper/20 bg-background p-3 shadow-2xl"><div class="min-h-[420px] border border-border bg-card p-7"><p class="text-[10px] font-semibold uppercase tracking-[0.2em] text-primary">YOUR DETAILS</p><h3 class="mt-3 font-display text-3xl">Register your visit</h3><div class="mt-10 grid min-h-48 place-items-center border border-dashed border-border bg-background/50 p-4"><div class="w-full space-y-3 px-2"><div class="border border-border px-3 py-2.5 text-xs"><span class="block text-[10px] uppercase tracking-[0.15em] text-muted-foreground">Name</span>Ananya S.</div><div class="border border-border px-3 py-2.5 text-xs"><span class="block text-[10px] uppercase tracking-[0.15em] text-muted-foreground">Phone</span>+91 XXXXX 34567</div><div class="border border-border px-3 py-2.5 text-xs"><span class="block text-[10px] uppercase tracking-[0.15em] text-muted-foreground">Email</span>yourname@company.com</div><p class="border border-primary px-3 py-2 text-center text-[10px] font-semibold uppercase tracking-[0.15em] text-primary">Register</p></div></div></div></div></div><div class="flex flex-col justify-center bg-paper p-8 text-ink md:p-12"><p class="text-xs font-semibold tracking-[0.2em] text-primary">STEP 02 / 04</p><h3 class="mt-5 font-display text-4xl">Register in seconds.</h3><p class="mt-5 max-w-md leading-7 text-ink/65">The visitor enters their name, phone number and email on their own phone. The relevant team member is alerted straight away.</p><p class="mt-10 border-t border-ink/15 pt-5 text-xs text-ink/60">Illustrative product flow · This QR is not a registration link</p></div></div>
<div data-panel-index="2" hidden class="grid min-h-[520px] border-x border-b border-paper/20 lg:grid-cols-[1.2fr_.8fr]"><div class="relative flex items-center justify-center overflow-hidden bg-ink p-8"><img src="/jewellery/showroom.jpg" alt="Customer using a showroom QR registration point" class="absolute inset-0 size-full object-cover opacity-40 grayscale"><div class="relative animate-drift w-[260px] border border-paper/20 bg-background p-3 shadow-2xl"><div class="min-h-[420px] border border-border bg-card p-7"><p class="text-[10px] font-semibold uppercase tracking-[0.2em] text-primary">VISITOR CHOICE</p><h3 class="mt-3 font-display text-3xl">Stay in touch?</h3><div class="mt-10 grid min-h-48 place-items-center border border-dashed border-border bg-background/50 p-4"><div class="w-full space-y-3 px-2"><div class="flex items-center justify-between border border-border px-3 py-2.5 text-xs"><span>WhatsApp updates</span><span class="border border-primary px-2 py-0.5 text-[10px] font-semibold text-primary">YES</span></div><div class="flex items-center justify-between border border-border px-3 py-2.5 text-xs"><span>Visit reminders</span><span class="border border-border px-2 py-0.5 text-[10px] text-muted-foreground">NO</span></div><p class="flex items-center gap-2 text-[10px] text-muted-foreground"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check size-3.5 text-primary" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg>Optional · your choice</p></div></div></div></div></div><div class="flex flex-col justify-center bg-paper p-8 text-ink md:p-12"><p class="text-xs font-semibold tracking-[0.2em] text-primary">STEP 03 / 04</p><h3 class="mt-5 font-display text-4xl">Opt-in stays optional.</h3><p class="mt-5 max-w-md leading-7 text-ink/65">The visitor can choose whether to receive further messages from your brand.</p><p class="mt-10 border-t border-ink/15 pt-5 text-xs text-ink/60">Illustrative product flow · This QR is not a registration link</p></div></div>
<div data-panel-index="3" hidden class="grid min-h-[520px] border-x border-b border-paper/20 lg:grid-cols-[1.2fr_.8fr]"><div class="relative flex items-center justify-center overflow-hidden bg-ink p-8"><img src="/jewellery/showroom.jpg" alt="Customer using a showroom QR registration point" class="absolute inset-0 size-full object-cover opacity-40 grayscale"><div class="relative animate-drift w-[260px] border border-paper/20 bg-background p-3 shadow-2xl"><div class="min-h-[420px] border border-border bg-card p-7"><p class="text-[10px] font-semibold uppercase tracking-[0.2em] text-primary">BRAND WHATSAPP</p><h3 class="mt-3 font-display text-3xl">Continue the conversation</h3><div class="mt-10 grid min-h-48 place-items-center border border-dashed border-border bg-background/50 p-4"><div class="w-full space-y-2.5 px-2"><div class="max-w-[85%] border border-border bg-card px-3 py-2 text-xs">Hi Ananya, thank you for visiting us today. — Team Elegance</div><div class="ml-auto max-w-[85%] border border-primary/40 bg-primary/10 px-3 py-2 text-xs">Loved the jhumka collection!</div><p class="flex items-center gap-2 pt-1 text-[10px] text-muted-foreground"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-message-circle size-3.5 text-primary" aria-hidden="true"><path d="M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719"></path></svg>WhatsApp opt-in confirmed</p></div></div></div></div></div><div class="flex flex-col justify-center bg-paper p-8 text-ink md:p-12"><p class="text-xs font-semibold tracking-[0.2em] text-primary">STEP 04 / 04</p><h3 class="mt-5 font-display text-4xl">Engage, with permission.</h3><p class="mt-5 max-w-md leading-7 text-ink/65">When a visitor opts in, your authorised team can reconnect through your brand’s WhatsApp channel.</p><p class="mt-10 border-t border-ink/15 pt-5 text-xs text-ink/60">Illustrative product flow · This QR is not a registration link</p></div></div></div>
</section>
<section id="why" class="bg-paper py-20 lg:py-28">
<div class="section-shell"><p class="text-xs font-semibold uppercase tracking-[0.25em] text-primary">The value grows with each visit</p><h2 class="mt-4 text-5xl tracking-normal">Useful today. More useful over time.</h2><p class="mt-6 max-w-2xl leading-7 text-muted-foreground">Keep each step practical: welcome visitors, make the team aware and give them a record they can refer to when it is appropriate to reconnect.</p><div class="mt-16 grid border-y border-border md:grid-cols-3 md:divide-x md:divide-border">
<article class="relative px-0 py-8 md:px-8"><span class="font-display text-5xl text-primary">Now</span><h3 class="mt-7 text-xl">Know who visited.</h3><p class="mt-3 text-sm leading-6 text-muted-foreground">QR registration creates a digital visitor record and alerts the relevant staff.</p></article>
<article class="relative px-0 py-8 md:px-8"><span class="font-display text-5xl text-sky">Next</span><h3 class="mt-7 text-xl">Continue the conversation.</h3><p class="mt-3 text-sm leading-6 text-muted-foreground">Your team can follow up with people who have chosen to share their details and receive messages.</p></article>
<article class="relative px-0 py-8 md:px-8"><span class="font-display text-5xl text-coral">Over time</span><h3 class="mt-7 text-xl">See the bigger picture.</h3><p class="mt-3 text-sm leading-6 text-muted-foreground">Review saved records and available reports to understand showroom activity.</p></article></div></div>
</section>
<section class="relative min-h-[620px] overflow-hidden"><img src="/jewellery/showroom.jpg" alt="Visitor scanning a QR code in a luxury jewellery showroom" class="image-story-photo absolute inset-0 size-full object-cover grayscale"/><div class="image-story-veil absolute inset-0"></div>
<div class="section-shell relative flex min-h-[620px] items-center py-20"><div class="max-w-xl"><p class="text-xs font-semibold uppercase tracking-[0.23em] text-primary">An in-store moment, not an online ad QR</p><h2 class="mt-5 text-5xl tracking-normal">Made for real showroom teams</h2><p class="mt-5 text-xl">Simple to put into practice.</p><p class="mt-5 leading-7 text-foreground/65">Place a QR at reception or a counter. Let visitors register on their own phones, while your team stays focused on the in-person experience.</p><div class="mt-10 grid grid-cols-2 gap-px bg-border border border-border"><div class="bg-background/90 p-5 backdrop-blur"><strong class="text-primary">No hardware</strong><p class="mt-2 text-xs leading-5 text-muted-foreground">No dedicated registration device required.</p></div><div class="bg-background/90 p-5 backdrop-blur"><strong class="text-primary">≈ 15 min</strong><p class="mt-2 text-xs leading-5 text-muted-foreground">Indicative standard setup time.</p></div><div class="bg-background/90 p-5 backdrop-blur"><strong class="text-primary">Staff alerts</strong><p class="mt-2 text-xs leading-5 text-muted-foreground">Let the relevant team member know a visitor has registered.</p></div><div class="bg-background/90 p-5 backdrop-blur"><strong class="text-primary">Visitor records</strong><p class="mt-2 text-xs leading-5 text-muted-foreground">Keep details available in the dashboard.</p></div></div></div></div>
</section>
<section id="trial" class="bg-primary py-20 text-ink lg:py-28">
<div class="section-shell grid gap-12 lg:grid-cols-[1fr_22rem] lg:items-end"><div><p class="text-xs font-bold uppercase tracking-[0.25em] text-deep">Put it to work in your showroom</p><h2 class="mt-5 max-w-3xl text-6xl leading-none tracking-normal">Start remembering every registered visit.</h2><p class="mt-7 max-w-2xl text-lg leading-8 text-ink/70">Test the QR registration and team notification flow with real showroom walk-ins during the paid trial.</p><div class="mt-10 flex flex-wrap gap-3 text-sm"><span class="border border-ink/20 px-4 py-2">15 days</span><span class="border border-ink/20 px-4 py-2">100 visitor bookings</span><span class="border border-ink/20 px-4 py-2">No dedicated hardware</span></div></div><div class="border border-ink/15 bg-foreground/55 p-7"><p class="text-xs font-semibold uppercase tracking-[0.2em] text-ink/60">Paid trial</p><p class="my-5 font-display text-7xl">₹49</p><p class="mb-7 text-sm text-ink/70">Try Hai Visitor in your own showroom.</p><a href="#trial" class="trial-cta inline-flex items-center justify-center gap-3 rounded-sm font-semibold transition-all duration-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:pointer-events-none disabled:opacity-50 bg-foreground text-background hover:-translate-y-0.5 hover:bg-foreground/90 min-h-14 px-8 text-base w-full">Start 15-day trial <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-arrow-up-right size-5" aria-hidden="true"><path d="M7 7h10v10"></path><path d="M7 17 17 7"></path></svg></a></div></div>
</section>
<section class="bg-paper py-20 lg:py-28">
<div class="section-shell"><p class="text-xs font-semibold uppercase tracking-[0.25em] text-deep">Common questions</p><h2 class="mt-4 text-5xl tracking-normal">A few quick answers.</h2><div class="mt-12 divide-y divide-border border-y border-border">
<details class="group py-6"><summary class="flex cursor-pointer list-none items-center justify-between gap-5 text-lg font-medium">Does the visitor scan the QR in the ad?<span class="text-primary transition-transform group-open:rotate-45">+</span></summary><p class="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">No. The registration QR is displayed inside your showroom. The QR shown here is only an illustration.</p></details>
<details class="group py-6"><summary class="flex cursor-pointer list-none items-center justify-between gap-5 text-lg font-medium">Is WhatsApp opt-in required?<span class="text-primary transition-transform group-open:rotate-45">+</span></summary><p class="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">The visitor chooses whether to opt in. Staff notification and saved registration details are separate from the visitor’s choice to receive messages from the brand.</p></details>
<details class="group py-6"><summary class="flex cursor-pointer list-none items-center justify-between gap-5 text-lg font-medium">Does it automatically send marketing campaigns or guarantee sales?<span class="text-primary transition-transform group-open:rotate-45">+</span></summary><p class="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">No. Hai Visitor supports registration, alerts and access to visitor records. Any later customer conversation is planned and carried out by your team.</p></details>
<details class="group py-6"><summary class="flex cursor-pointer list-none items-center justify-between gap-5 text-lg font-medium">What does the ₹49 trial include?<span class="text-primary transition-transform group-open:rotate-45">+</span></summary><p class="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">A 15-day paid trial with 100 visitor bookings. Check the registration page for current terms before paying.</p></details></div></div>
</section>
<footer class="border-t border-paper/10 bg-deep py-12 text-paper">
<div class="section-shell flex flex-col items-start justify-between gap-8 sm:flex-row sm:items-center"><a href="#top" class="brand-lockup brand-lockup--compact text-paper" aria-label="Hai Visitor home"><span class="brand-lockup__emblem fu-logo" aria-hidden="true"><img src="/v-mark.png" alt="" /></span><span class="brand-lockup__name">H<span>ai</span> Visitor</span></a><p class="text-xs uppercase tracking-[0.16em] text-paper/60">Visit. Interact. Build. Engage.</p><p class="text-xs text-paper/60">Zodopt Technology Solutions Pvt Ltd</p></div></footer>
</main>

<!-- Sticky CTA (all screen sizes), same as the main landing page -->
<div class="sticky-cta">
  <a class="btn btn-primary trial-cta" href="#trial">Start 15-Day Trial for ₹49 →</a>
</div>

<!-- WhatsApp float -->
<a class="wa-float" href="${WHATSAPP_URL}" target="_blank" rel="noopener noreferrer" aria-label="Chat on WhatsApp"><img src="/whatsapp-icon.png" alt="WhatsApp" /></a>

<!-- TRIAL SIGNUP POPUP -->
${TRIAL_MODAL_HTML}
`;

/* Walkthrough tabs: clicking a tab shows its step panel (the export's
   main.js). Returns a cleanup function. */
const initWalkthrough = () => {
  const tabs = document.querySelectorAll('.fu [data-tab-index]');
  const panels = document.querySelectorAll('.fu [data-panel-index]');
  if (!tabs.length || !panels.length) return () => {};

  const ACTIVE = ['bg-primary', 'text-primary-foreground'];
  const INACTIVE = ['bg-ink', 'text-paper/65', 'hover:bg-paper', 'hover:text-ink'];

  const onTabClick = (e) => {
    const target = e.currentTarget.getAttribute('data-tab-index');
    tabs.forEach((t) => {
      const selected = t === e.currentTarget;
      t.setAttribute('aria-selected', selected ? 'true' : 'false');
      ACTIVE.forEach((c) => t.classList.toggle(c, selected));
      INACTIVE.forEach((c) => t.classList.toggle(c, !selected));
    });
    panels.forEach((p) => { p.hidden = p.getAttribute('data-panel-index') !== target; });
  };
  tabs.forEach((tab) => tab.addEventListener('click', onTabClick));

  return () => tabs.forEach((tab) => tab.removeEventListener('click', onTabClick));
};

export default function FurnitureLanding() {
  useEffect(() => {
    loadMetaPixel();
    const cleanupWalkthrough = initWalkthrough();
    const cleanupTrial = initTrialSignup({ landing: 'furniture' });
    return () => {
      cleanupWalkthrough();
      cleanupTrial();
    };
  }, []);

  return <div className="fu lp" dangerouslySetInnerHTML={{ __html: BODY_HTML }} />;
}
