import { sendEmail } from "../utils/mailer.js";
import { generateVisitorPassImage } from "./visitor-pass-image.js";

/* ======================================================
   SUPER SAFE IST FORMATTER
   Supports:
   ✔ 2026-01-06 10:42:44        (Already IST)
   ✔ 2026-01-06T11:20:20.000Z   (UTC ISO)
   ✔ Date object
   ✔ Prevents crashes
====================================================== */
const formatIST = (value) => {
  if (!value) return "-";

  // If Date object
  if (value instanceof Date && !isNaN(value.getTime())) {
    return value.toLocaleString("en-IN", {
      timeZone: "Asia/Kolkata",
      day: "2-digit",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
      hour12: true
    });
  }

  // If not string, try convert
  if (typeof value !== "string") {
    try {
      const d = new Date(value);
      if (!isNaN(d)) {
        return d.toLocaleString("en-IN", {
          timeZone: "Asia/Kolkata",
          day: "2-digit",
          month: "short",
          year: "numeric",
          hour: "2-digit",
          minute: "2-digit",
          hour12: true
        });
      }
    } catch {}
    return "-";
  }

  // If ISO (contains T)
  if (value.includes("T")) {
    try {
      const d = new Date(value);
      if (isNaN(d)) return "-";

      return d.toLocaleString("en-IN", {
        timeZone: "Asia/Kolkata",
        day: "2-digit",
        month: "short",
        year: "numeric",
        hour: "2-digit",
        minute: "2-digit",
        hour12: true
      });
    } catch {
      return "-";
    }
  }

  // MySQL Format YYYY-MM-DD HH:MM:SS
  try {
    const [date, time] = value.split(" ");
    if (!date || !time) return value;

    const [y, mo, d] = date.split("-");
    let [h, m] = time.split(":");

    let hour = parseInt(h, 10);
    const suffix = hour >= 12 ? "PM" : "AM";
    hour = hour % 12 || 12;

    const monthNames = [
      "Jan","Feb","Mar","Apr","May","Jun",
      "Jul","Aug","Sep","Oct","Nov","Dec"
    ];

    return `${d} ${monthNames[mo - 1]} ${y}, ${hour}:${m} ${suffix}`;
  } catch {
    return value;
  }
};

/* ======================================================
   EMAIL FOOTER — FINAL APPROVED STYLE
====================================================== */
export const emailFooter = (company = {}) => {
  const companyName = company?.name || "Promeet";
  const logo = company?.logo_url || company?.logo || null;

  return `
<br/>

<div style="
  margin-top:18px;
  padding-top:14px;
  border-top:1px solid #ddd;
  font-family:Arial, Helvetica, sans-serif;
">

  <div style="
    display:flex;
    align-items:center;
    gap:12px;
    margin-bottom:6px;
  ">

    ${
      logo
        ? `<img 
            src="${logo}" 
            alt="${companyName} Logo"
            height="54"
            style="
              border-radius:10px;
              border:1px solid #eee;
              background:#fff;
              padding:6px;
            "
          />`
        : ""
    }

    <strong style="font-size:16px; color:#222;">
      ${companyName}
    </strong>
  </div>

  <p style="
    font-size:13px;
    color:#666;
    line-height:1.6;
    margin:0;
  ">
    This email was automatically generated by the Promeet Visitor Management Platform.
    If you did not perform this action,
    please contact your administrator immediately.
  </p>

</div>
`;
};

/* ======================================================
   SEND VISITOR PASS EMAIL
====================================================== */
export const sendVisitorPassMail = async ({ company = {}, visitor = {} }) => {
  if (!visitor.email) return;

  let imageBuffer = null;

  try {
    imageBuffer = await generateVisitorPassImage({ company, visitor });
  } catch (err) {
    console.error("VISITOR PASS IMAGE ERROR:", err.message);
  }

  try {
    await sendEmail({
      to: visitor.email,
      subject: `Your Visitor Pass – ${company.name || "Promeet"}`,
      html: `
        <p>Hello <b>${visitor.name || "Visitor"}</b>,</p>

        <p>Your visitor pass has been generated successfully.</p>

        <p>
          <b>Visitor ID:</b> ${visitor.visitorCode || "-"}<br/>
          <b>Company:</b> ${company.name || "Promeet"}<br/>
          <b>Check-in:</b> ${formatIST(visitor.checkIn)} (IST)
        </p>

        <p>Please show the attached visitor pass at the reception.</p>

        ${emailFooter(company)}
      `,
      attachments: imageBuffer
        ? [
            {
              filename: "visitor-pass.png",
              content: imageBuffer,
              contentType: "image/png"
            }
          ]
        : []
    });
  } catch (err) {
    console.error("VISITOR MAIL ERROR:", err.message);
  }
};
